name: Upload Maestro test results
description: Upload Maestro test results as artifacts

inputs:
  id:
    description: 'artifact ID'
    required: true

runs:
  using: composite
  steps:
    - name: Test Report
      uses: dorny/test-reporter@v2
      continue-on-error: true
      with:
        name: Maestro E2E test report ${{ inputs.id }}
        path: ${{ github.workspace }}/examples/bare-example/e2e_results/report.xml
        reporter: java-junit

    - name: Upload report
      uses: actions/upload-artifact@v4
      continue-on-error: true
      with:
        name: Maestro E2E recordings and screenshots ${{ inputs.id }}
        path: |
          ${{ github.workspace }}/examples/bare-example/e2e_results/*.mp4
          ${{ github.workspace }}/examples/bare-example/e2e_results/*.png
          testRecording.mp4

    - name: Upload report
      uses: actions/upload-artifact@v4
      continue-on-error: true
      with:
        name: Maestro E2E test logs API ${{ inputs.id }}
        path: |
          ~/.maestro/tests/**
